### ISSUE TITLE
Fix "Something Went Wrong" message when plan has portals with identical names

### ISSUE THREAD

**Issue by mike40033** [mike40033/iitc-57Cell#9]
Eg, "Let Nature Feed Itself": https://intel.ingress.com/intel?ll=-31.927584,115.812584&z=17&pll=-31.927584,115.812584 and "Let Nature Feed Itself": https://intel.ingress.com/intel?ll=-31.928044,115.811473&z=17&pll=-31.928044,115.811473

**Comment by mikehdugeo** [comment]
fixed!
